apiVersion: v1
kind: Service
metadata:
  name: catalog-service
spec:
  selector:
    app: catalog
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30080 # optional, must be in 30000–32767
  type: NodePort
