apiVersion: v1
kind: Service
metadata:
  name: ui-service
spec:
  selector:
    app: ui
  type: NodePort
  ports:
    - port: 80 # service port inside cluster
      targetPort: 8080 # container port
      nodePort: 30801 # optional host port on Minikube
